receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:

exporters:
  # The debug exporter streams formatted human-readable payloads to docker logs
  debug:
    verbosity: detailed
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  otlphttp/openlit:
    endpoint: http://openlit:4318
  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/tempo, otlphttp/openlit]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/prometheus, otlphttp/openlit]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/loki, otlphttp/openlit]
